#!/bin/bash
if [ "$HOSTNAME" == "miner0" ]; then
	GPU="NVIDIA"
else
	GPU="AMD"
fi
CMD="sudo g++  main.cpp -std=c++11 -ljsoncpp -o /usr/local/bin/whattomine -D$GPU -DETHWALLET=$ETHWALLET -DETCWALLET=$ETCWALLET -DETPWALLET=$ETPWALLET"
echo $CMD
$CMD
